# a simple Travis-CI Free Pascal example
language: generic

sudo: true
group: travis_latest

os:
  - linux
  - osx

git:
  depth: 3
  quiet: true


before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      else
        sudo apt -q install fp-compiler;
      fi

install:
  - cd bin
  - cmake ..
  - cmake --build .
  
script:
  - ctest -V

