# a simple Travis-CI Free Pascal example
language: generic
fast_finish: true

sudo: true
group: travis_latest

os:
  - linux
  - osx

git:
  depth: 3


before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install fpc;
      else
        sudo apt install fp-compiler;
      fi

install:
  - cd bin
  - cmake ..
  - make
  
script:
  - make test

